package com.example.queerfy.model

data class Property(
    val id: Int,
    val name: String,
    val active: Boolean,
    val dailyPrice: Double,
    val filterDate: String,
    val latitude: String,
    val longitude: String,
    val idUser: Int,
    val description: String,
    val likes: Int,
    val state: String,
    val uf: String,
    val cep: String,
    val street: String,
    val houseNumber: String,
    val addressComplement: String,
    val city: String,
    val propertyType: String,
    val spaceType: String,
    val guestsQuantity: String,
    val bedsQuantity: String,
    val roomQuantity: String,
    val bathroomQuantity: String,
    val haveWifi: Boolean,
    val haveKitchen: Boolean,
    val haveSuite: Boolean,
    val haveGarage: Boolean,
    val haveAnimals: Boolean,
)